# -*- encoding: utf-8 -*-
{
    'name': "OVIS",
    'version': '12.0.0',
    'summary': 'Custom Module For OVIS.',
    'category': 'Other',
    'description': """Custom Module For OVIS.""",
    'author': 'Cayprol',
    "depends" : ['base',
                 'mrp',
                 'product',
                 'purchase',
                 'sale',
                 'web',
                 'l10n_tw',
                 'l10n_cn_province',
                 'report_qweb_element_page_visibility',
                 'sale_quotation_number',
                 ],
    'data': [
             'security/ir.model.access.csv',
             'views/inherit_account_view.xml',
             'views/inherit_product_template_only_form_views.xml',
             'views/product_views.xml',
             'views/inherit_purchase_views.xml',
             'views/inherit_res_partner_views.xml',
             'views/inherit_sale_views.xml',
             'views/inherit_stock_picking_views.xml',
             'views/override_account_view.xml',
             'report/TEST.xml',
             'report/TEST_templates.xml',
             'wizard/inherit_stock_backorder_confirmation_views.xml',
             ],
    "images": [],
    'license': 'LGPL-3',
    'qweb': [
            ],  
    
    'installable': True,
    'application'   : True,
    'auto_install'  : False,
}
