# -*- coding: utf-8 -*-

from odoo import models, fields, api

class PurchaseOrderInherited(models.Model): 

	_inherit = 'purchase.order'

	note_exception = fields.Text(string='Exception Note', help='Text of exception when generating PO for future validation or approval') 

	exception = fields.Boolean(string='Exception', help='Set to True if this PO is in exception and not generated by regular workflow')





